import Head from 'next/head'
import { BiUserPlus } from "react-icons/bi";
import Table from '../components/table';

export default function Home() {
  return (
    <section>
      <Head>
        <title>SortingHat Application</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='py-5'>
        <h1 className='text-xl md:text-5xl text-center font-bold py-10'>Interviewers List</h1>

        {/* collapsable form */}

        {/* table */}
        <div className="container mx-auto">
          <Table></Table>
        </div>

      </main>
    </section>
  )
}